### ISSUE TITLE
how to use in 2.0.7

### ISSUE THREAD

**Issue by patrickpeng2091** [emizentech/magento2-customordernumber#1]
When I use this plugin

var/report   display

s:1138:"Fatal Error: 'Uncaught TypeError: Argument 1 passed to EmizenTech\CustomOrderNumber\Observer\changeOrderId::__construct() must implement interface Psr\Log\LoggerInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /var/www/magento2/app/code/EmizenTech/CustomOrderNumber/Observer/ChangeOrderId.php:18
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(97): EmizenTech\CustomOrderNumber\Observer\changeOrderId->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('EmizenTech\Cust...', Array)
#2 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('EmizenTech\Cust.' in '/var/www/magento2/app/code/EmizenTech/CustomOrderNumber/Observer/ChangeOrderId.php' on line 18";

**Comment by nathanwatts** [comment]
Class name of observer ChangeOrderId should be:

ChangeOrderId

not

changeOrderId
